### ISSUE TITLE
ドラマの新規追加API

### ISSUE THREAD

**Issue by mediasciencejp** [mediasciencejp/review-system#1]
- [ ] エンドポイントに項目をPostすれば、DBに情報が格納される
- [ ] 入力項目のバリデーション機能の実装
    - [ ] バリデーションメッセージの日本語化
- [ ] ログインチェック
- [ ] エラーハンドリング

**Comment by sundaycrafts** [comment]
## ドラマに必要なプロパティ

* ドラマ名
* 放送時期
* パーマリンク (URL用文字列)
* 読み方
* 放送局
* 開始日
* 終了日 (optional)

## 仕様

- [ ] 管理者が、正規のドラマ情報を送信すると、新規でドラマが追加される (201)
- [ ] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: ドラマ名が未入力)
- [ ] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: パーマリンクが未入力)
- [ ] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: 放送局が未入力)
- [ ] 管理者が、ドラマの放送時期が未定のドラマを送信すると、ドラマは登録できない (400 エラー)
- [ ] 管理者が、開始日が未定のドラマを送信すると、ドラマは登録できない (400 エラー)
- [ ] 管理者が、重複したドラマ名を登録すると、400 エラーが返る (リメイク版はSEOの観点からも必ず異なる名前が付く)
- [ ] 管理者は、複数の放送時期を指定したドラマ情報を送信できる (201)

**Comment by sundaycrafts** [comment]
668c66c でエラーが出ていた controller のテストを削除しています (中身はカラ)。

**Comment by sundaycrafts** [comment]
各種仕様は単体テストで、 e2e テストではほぼエンドポイントを作っただけ。

**Comment by mediasciencejp** [comment]
## ドラマに必要なプロパティの扱いについて

放送局と放送時期はManyToManyになるので後回し。
まずは以下の実装

* ドラマ名
* パーマリンク (URL用文字列)
* 読み方
* 開始日
* 終了日 (optional)

## 仕様

- [x] 管理者が、正規のドラマ情報を送信すると、新規でドラマが追加される (201)
- [x] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: ドラマ名が未入力)
- [x] 【追加】管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: ドラマ名がゼロ文字)
- [ ] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: パーマリンクが未入力)
- [ ] 管理者が、不正なドラマ情報を送信すると、400 エラーが返る (ex: 放送局が未入力)
- [ ] 管理者が、ドラマの放送時期が未定のドラマを送信すると、ドラマは登録できない (400 エラー)
- [ ] 管理者が、開始日が未定のドラマを送信すると、ドラマは登録できない (400 エラー)
- [ ] 管理者が、重複したドラマ名を登録すると、400 エラーが返る (リメイク版はSEOの観点からも必ず異なる名前が付く)
- [ ] 管理者は、複数の放送時期を指定したドラマ情報を送信できる (201)
